pipeline {
   agent any

   stages {
      stage("Clone Code") {
         steps {
            echo "Cloning the code"
            git url: "https://github.com/Yimenghub/yimeng_test_django.git", branch: "main"
         }
      }

      stage("Build") {
         steps {
            echo "Building the Docker image"
            sh "docker build -t mydjango-python-app ."
         }
      }

      stage("Push to Docker Hub") {
         steps {
            echo "Pushing the Docker image to Docker Hub"
            withCredentials([usernamePassword(credentialsId: "dckr_pat_a3WASkRMlX9QpLee2lVNfVgHVig", passwordVariable: "yimeng2000", usernameVariable: "yoejo")]) {
               sh "docker tag mydjango-python-app ${env.yoejo}/mydjango-python-app:latest"
               sh "docker login -u ${env.yoejo} -p ${env.yimeng2000}"
               sh "docker push ${env.yoejo}/mydjango-python-app:latest"
            }
         }
      }

      stage("Deploy") {
         steps {
            echo "Deploying the container"
            sh "docker-compose down && docker-compose up -d"
         }
      }
   }
}